### ISSUE TITLE
[Bug] documentation for negation operator has an invalid example 

### ISSUE THREAD

**Issue by zswanson** [kyverno/website#610]
### Page link

https://kyverno.io/docs/writing-policies/validate/#anchors

### Description

The documentation for the Negation operator `X()` says that `the value should ideally be set to null`, and then provides a snippet of sample code showing an empty value. 

```
e.g. Hostpath tag cannot be defined.
    X(hostPath):
```

In testing with the Kyverno 1.7.3 CLI I have found that this is invalid. The following expressions will cause a SIGSEGV fault in the CLI when evaluated against annotations or labels in a resource. I did not test in the Kyverno controller (cluster) but I imagine it would panic there too. 

```
    # this produces a SIGSEGV
    X(hostPath): null
```

```
    # this produces a SIGSEGV
    # the tilde char is the yaml null character
    X(hostPath): ~
```

```
    # this produces a SIGSEGV
    X(hostPath): 
```

This seems to only be valid with some sort of string as the value. That can be `""` or `"null"` or "*"` but a string _must_ be provided. Could be possible that this behaves different for dictionary/array structures, I did not test those cases.

Crash log
```
Executing ingress-gateway-external...
applying 1 policy to 4 resources...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xf8 pc=0x105f4516c]

goroutine 1 [running]:
github.com/kyverno/kyverno/pkg/policy.isLabelAndAnnotationsString.func1(0x7?)
	github.com/kyverno/kyverno/pkg/policy/validate.go:592 +0x26c
github.com/kyverno/kyverno/pkg/policy.isLabelAndAnnotationsString({{0x140026378e0, 0x20}, {0x0, 0x0, 0x0}, {{0x14004535200, 0x1, 0x4}, {0x0, 0x0, ...}, ...}, ...})
	github.com/kyverno/kyverno/pkg/policy/validate.go:607 +0x44
github.com/kyverno/kyverno/pkg/policy.Validate({0x107515568, 0x140044b6680}, {0x0, 0x0}, 0x1, 0x2?)
	github.com/kyverno/kyverno/pkg/policy/validate.go:307 +0xb88
github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test.applyPoliciesFromPath({0x107508ca8, 0x14000b0d940}, {0x140006b7500, 0x603, 0x700}, 0x0?, {0x16ba930cd, 0x27}, 0x1074fe4c8?, 0x28b?, ...)
	github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test/test_command.go:850 +0xa5c
github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test.getLocalDirTestFiles({0x107508ca8, 0x14000b0d940}, {0x16ba930cd, 0x27}, {0x10612108f, 0x11}, 0x106ea8f80?, 0x14005183910, 0x14000c1f928?, 0x1059ba9f4?)
	github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test/test_command.go:477 +0x440
github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test.testCommandExecute({0x140009fdd10, 0x1, 0x0?}, {0x10612108f, 0x11}, {0x0, 0x0}, {0x0, 0x0})
	github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test/test_command.go:429 +0x2c8
github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test.Command.func1(0x140005e0a00?, {0x140009fdd10, 0x1, 0x1})
	github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/test/test_command.go:218 +0x15c
github.com/spf13/cobra.(*Command).execute(0x140005e0a00, {0x140009fdce0, 0x1, 0x1})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x140005e0280)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	github.com/kyverno/kyverno/cmd/cli/kubectl-kyverno/main.go:35 +0xb0
```

### Expected behavior

Update wording and example to something like this:

```
The tag cannot be specified. The value of the tag is not evaluated (use exclamation point to negate a value). The value should ideally be set to "null".
e.g. Hostpath tag cannot be defined.    
  X(hostPath): "null"
```

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1662211321407919

**Comment by chipzoller** [comment]
Closed in PR #625
