### ISSUE TITLE
[Render] Disregard files used for kuttl tests

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#822]
### Description

Rendering of policies is broken when encountering certain files needed for kuttl tests, for example a policy assert file. The `render` program is not able to distinguish between the "real" policy and a fragment of a policy. This may lead to a panic when it encounters this policy fragment:

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.getPolicyType({0xc0012e5c80?, 0x72?})
        C:/Users/Chip/Documents/My Git/kyvernowebsite/render/render.go:50 +0x1aa
main.newPolicyData(0xc001c261a0, {0xc0012e5c80, 0x72}, {0xc001398d90, 0x61}, {0xc000091840, 0x34})
        C:/Users/Chip/Documents/My Git/kyvernowebsite/render/render.go:68 +0x5e
main.render(0xc0001e0200, {0xc000032138, 0x17})
        C:/Users/Chip/Documents/My Git/kyvernowebsite/render/render.go:160 +0xb9b
main.init.0.func1(0xc0001ec580?, {0xc0001cdf80?, 0x3?, 0x3?})
        C:/Users/Chip/Documents/My Git/kyvernowebsite/render/root.go:30 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc0001ec580, {0xc000068050, 0x3, 0x3})
        C:/Users/Chip/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ec580)
        C:/Users/Chip/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/Chip/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
```

We need to modify `render` to somehow figure out how to distinguish the "real" policy in the folder.

**Comment by chipzoller** [comment]
A possible solution here might be to do the following:

1. Only render 1 policy per directory. Given the changes needed to support Artifact Hub scraping, there will be a 1:1 mapping of folder to policy.
2. Only render a policy that has an annotation with key beginning with `policies.kyverno.io`. These [annotations](https://github.com/kyverno/policies/wiki/Kyverno-annotations) are for use on our website as well as Artifact Hub and we will (or should) never add these to any policy assertion files for kuttl testing.

**Comment by chipzoller** [comment]
All you have to do is run the `render` program pointed at the kyverno/policies git repo.

**Comment by chipzoller** [comment]
I'd recommend solution number two.

**Comment by VedRatan** [comment]
Okay, I would like to work on this one. @chipzoller

**Comment by chipzoller** [comment]
@VedRatan do you need any assistance here?

**Comment by chipzoller** [comment]
@VedRatan any progress?

**Comment by VedRatan** [comment]
Working on the issue will be raising PR in a day or two.

**Comment by VedRatan** [comment]
> 

so I have to run `render https://github.com/kyverno/policies.git` to check my changes? @chipzoller

**Comment by chipzoller** [comment]
There are currently no kuttl tests here because doing so breaks rendering. I recommend creating a small demo repo yourself and take a few folders from here, and then try adding a kuttl test to one of them to test changes. The `render` utility should only detect and render the Kyverno policy which has any annotations beginning with key `policies.kyverno.io`. It should not panic.

**Comment by VedRatan** [comment]
So, I have to create another repo and add some tests and build the website again, if the render utility fails the website should not render, if not the website should render, am I right at this point? @chipzoller.

**Comment by chipzoller** [comment]
No, this doesn't have anything to do with the website. You make your changes to the `render` program. The test is can `render` be pointed to another git repo which contains "real" Kyverno policy in addition to kuttl tests. I would create a separate repo and put some directories from kyverno/policies in there, and then put some junk kuttl test files there as well. See if `render` can cope with that.

**Comment by VedRatan** [comment]
Yes please, it would be helpful

**Comment by chipzoller** [comment]
I'm saying this is what _you_ should do.

**Comment by VedRatan** [comment]
@chipzoller could you please help me with the command to run this render program, I am trying to run `go run render/main.go` but its showing error that rootCmd not found in the main.go file of render folder.

**Comment by VedRatan** [comment]
@chipzoller  could you please verify the repo https://github.com/VedRatan/RenderTest-Kyverno.git.

**Comment by VedRatan** [comment]
after running the command `./render https://github.com/VedRatan/RenderTest-Kyverno.git/main content/en/policies` its pulling the repo content inside the path specified. Not showing error that has to be shown

**Comment by chipzoller** [comment]
You need to put all the files in the same directory. No subdirectories.

**Comment by VedRatan** [comment]
now can you verify?

**Comment by chipzoller** [comment]
This looks correct for a test. The render utility should only render `disallow-latest-tag.yaml` and disregard everything else.

**Comment by VedRatan** [comment]
its rendering policy-assert too.

**Comment by chipzoller** [comment]
Then that is the behavior we do not want.

**Comment by VedRatan** [comment]
oh so we don't want the kuttl tests to be rendered?

**Comment by chipzoller** [comment]
No, this is the entire reason this issue is open, @VedRatan. We DO NOT want the render utility to consider any of the kuttl test files. We want it to only render one policy in each folder which represents the sample policy being tested. How the utility will identify which is the "real" policy to render will be as I described above.

**Comment by VedRatan** [comment]
Ok, sure.
